FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["MoviesApiChallenge.csproj", "."]
COPY ["appsettings.json", "."]
RUN dotnet restore "./MoviesApiChallenge.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MoviesApiChallenge.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MoviesApiChallenge.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MoviesApiChallenge.dll"]

FROM build AS builddb
WORKDIR /src
COPY ["MoviesApiChallenge.csproj", "./"]
COPY entrypoint.sh entrypoint.sh
RUN dotnet tool install --global dotnet-ef
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet restore "./MoviesApiChallenge.csproj"
COPY . .
WORKDIR "/src/."
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh