version: "4.10.1"
services:
    api:
        image: moviesapichallenge
        build: .
        ports:
            - "8080:80"
        depends_on:
          - moviesdb
    moviesdb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "StevenCheco@1909"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"