version: "3.9"
services:
    web:
        image: cruddockercompose
        build: .
        ports:
            - "8080:80"
        depends_on:
          - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "YourPasswordHere0011"
            ACCEPT_EULA: "Y"