version: "3.9"
services:
    api:
        image: moviesapichallenge
        build: .
        ports:
            - "8080:80"
        depends_on:
          - db
    moviesdb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "admin123"
            ACCEPT_EULA: "Y"